version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    network_mode: "host"
  kibana:
    image: kibana:latest
    network_mode: "host"
  logstash:
    image: logstash:latest
    network_mode: "host"
    volumes:
     - ./conf:/home/logstash/conf


