version: '2'

services:
  elasticsearch:
    image: elasticsearch:2
    ports:
      - "9200:9200"
      - "9300:9300"
    command: "elasticsearch -Des.cluster.name='graylog'"
  logstash:
    image: logstash:latest
    links:
      - elasticsearch:elasticsearch
      - graylog:graylog
    ports:
      - "12202/udp:12201/udp"
    volumes:
     - ./conf:/home/logstash/conf
  mongodb:
    image: mongo:2
  graylog:
    image: graylog2/server
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"

